[versions]
androidGradlePlugin = "9.0.0"
kotlin = "2.3.10"
spotless = "8.2.1"
appcompat = "1.7.1"
constraintlayout = "2.2.1"
googleGmsCodeScanner = "16.1.0"
material = "1.13.0"
activityKtx = "1.12.4"
browser = "1.9.0"
recyclerview = "1.4.0"

[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
google-gms-code-scanner = { group = "com.google.android.gms", name = "play-services-code-scanner", version.ref = "googleGmsCodeScanner" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activityKtx" }
androidx-browser = { group = "androidx.browser", name = "browser", version.ref = "browser" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
diffplug-spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
